# Configure value for OpenVPN
openvpn:
  aws:
    instance: i-xxx
    bucket: "automations"
    path: "build/ovpn/clients"

  # ovpn servicer configuration
  server:
    host: "123.123.123.123"
    port: 1194
    protocol: udp

  # Configuration for openvpn clients
  clients:
    # Number of days to expire client certs
    expire: 30
    routes:
      - 10.10.10.0