# This section configures the machine
machine:
  ssh:
    enabled: false

  swap:
    enabled: false
    ## Size of the swapfile to create
    ## $size * 1MB
    size: "65536"

  proxy:
    # Enable this if the machine is running behind corp proxy
    enabled: false
    http_endpoint: http://proxy:3128/
    https_endpoint: http://proxy:3128/
    exclusions: "169.254.169.254"

  docker:
    local_registry:
      enabled: false

    # Authentication for private docker repositories
    repositories:
      - name: registry.com
        username: test
        password: test

  # IP address to listen all exposed services on
  listen_ip: 0.0.0.0

  # Force update the machine config files even if they exist
  force_update_configs: false