name: Distribution Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run:
          make build
      - uses: actions/upload-artifact@v3
        with:
          name: menv-distributions
          path: ./menv-*.zip
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload nightly ./build.sh --clobber;
          gh release upload nightly ./menv-*.zip --clobber;
